import { Character } from './entities/character.entity';

export const characters = (): Character[] => [
  {
    id: 'ryu',
    order: 1,
    name: 'Ryu',
    stamina: 1000,
    stun: 1000,
    country: 'Japan',
  },
  {
    id: 'ken',
    order: 2,
    name: 'Ken',
    stamina: 1000,
    stun: 1000,
    country: 'USA',
  },
  {
    id: 'e-honda',
    order: 3,
    name: 'Edmond Honda',
    stamina: 1050,
    stun: 1100,
    country: 'Japan',
  },
  {
    id: 'ibuki',
    order: 4,
    name: 'Ibuki',
    stamina: 900,
    stun: 950,
    country: 'Japan',
  },
  {
    id: 'makoto',
    order: 5,
    name: 'Makoto',
    stamina: 1000,
    stun: 1050,
    country: 'Japan',
  },
  {
    id: 'dudley',
    order: 6,
    name: 'Dudley',
    stamina: 1050,
    stun: 1050,
    country: 'UK',
  },
  {
    id: 'seth',
    order: 7,
    name: 'Seth',
    stamina: 800,
    stun: 900,
    country: 'None',
  },
  {
    id: 'gouken',
    order: 8,
    name: 'Gouken',
    stamina: 1000,
    stun: 1000,
    country: 'Japan',
  },
  {
    id: 'akuma',
    order: 9,
    name: 'Akuma',
    stamina: 850,
    stun: 850,
    country: 'Japan',
  },
  {
    id: 'gen',
    order: 10,
    name: 'Gen',
    stamina: 900,
    stun: 900,
    country: 'China',
  },
  {
    id: 'dan',
    order: 11,
    name: 'Dan',
    stamina: 1000,
    stun: 900,
    country: 'Hong_Kong',
  },
  {
    id: 'sakura',
    order: 12,
    name: 'Sakura',
    stamina: 950,
    stun: 1000,
    country: 'Japan',
  },
  {
    id: 'yun',
    order: 13,
    name: 'Yun',
    stamina: 900,
    stun: 1000,
    country: 'Hong_Kong',
  },
  {
    id: 'juri',
    order: 14,
    name: 'Juri',
    stamina: 950,
    stun: 950,
    country: 'South_Korea',
  },
  {
    id: 'chun-li',
    order: 15,
    name: 'Chun-Li',
    stamina: 900,
    stun: 1050,
    country: 'China',
  },
  {
    id: 'dhalsim',
    order: 16,
    name: 'Dhalsim',
    stamina: 900,
    stun: 900,
    country: 'India',
  },
  {
    id: 'abel',
    order: 17,
    name: 'Abel',
    stamina: 1050,
    stun: 1050,
    country: 'France',
  },
  {
    id: 'c-viper',
    order: 18,
    name: 'Crimson Viper',
    stamina: 900,
    stun: 950,
    country: 'USA',
  },
  {
    id: 'm-bison',
    order: 19,
    name: 'M. Bison',
    stamina: 1000,
    stun: 950,
    country: 'None',
  },
  {
    id: 'sagat',
    order: 20,
    name: 'Sagat',
    stamina: 1050,
    stun: 1000,
    country: 'Thailand',
  },
  {
    id: 'cammy',
    order: 21,
    name: 'Cammy',
    stamina: 950,
    stun: 950,
    country: 'UK',
  },
  {
    id: 'dee-jay',
    order: 22,
    name: 'Dee Jay',
    stamina: 1000,
    stun: 1000,
    country: 'Jamaica',
  },
  {
    id: 'cody',
    order: 23,
    name: 'Cody',
    stamina: 1000,
    stun: 1050,
    country: 'USA',
  },
  {
    id: 'guy',
    order: 24,
    name: 'Guy',
    stamina: 1000,
    stun: 950,
    country: 'USA',
  },
  {
    id: 'hakan',
    order: 25,
    name: 'Hakan',
    stamina: 1050,
    stun: 1100,
    country: 'Turkey',
  },
  {
    id: 'yang',
    order: 26,
    name: 'Yang',
    stamina: 900,
    stun: 1000,
    country: 'Hong_Kong',
  },
  {
    id: 'guile',
    order: 27,
    name: 'Guile',
    stamina: 1000,
    stun: 900,
    country: 'USA',
  },
  {
    id: 'blanka',
    order: 28,
    name: 'Blanka',
    stamina: 1000,
    stun: 950,
    country: 'Brazil',
  },
  {
    id: 'zangief',
    order: 29,
    name: 'Zangief',
    stamina: 1100,
    stun: 1100,
    country: 'USSR',
  },
  {
    id: 'rufus',
    order: 30,
    name: 'Rufus',
    stamina: 1050,
    stun: 950,
    country: 'USA',
  },
  {
    id: 'el-fuerte',
    order: 31,
    name: 'El Fuerte',
    stamina: 900,
    stun: 1000,
    country: 'Mexico',
  },
  {
    id: 'vega',
    order: 32,
    name: 'Vega',
    stamina: 1000,
    stun: 900,
    country: 'Spain',
  },
  {
    id: 'balrog',
    order: 33,
    name: 'Balrog',
    stamina: 1050,
    stun: 1000,
    country: 'USA',
  },
  {
    id: 'fei-long',
    order: 34,
    name: 'Fei Long',
    stamina: 1000,
    stun: 1050,
    country: 'Hong_Kong',
  },
  {
    id: 't-hawk',
    order: 35,
    name: 'T. Hawk',
    stamina: 1100,
    stun: 1100,
    country: 'Mexico',
  },
  {
    id: 'adon',
    order: 36,
    name: 'Adon',
    stamina: 950,
    stun: 1000,
    country: 'Thailand',
  },
  {
    id: 'rose',
    order: 37,
    name: 'Rose',
    stamina: 950,
    stun: 1000,
    country: 'Italy',
  },
];
